# Site settings
title: Louis Le Toumelin personal website
email: louis.letoumelin at gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Work in progress
baseurl: "/" # the subpath of your site, e.g. /blog "/urban-theme"
url: "http://louisletoumelin.github.io" # the base hostname & protocol for your site
twitter_username: louisletoumelin
github_username:  louisletoumelin

# Build settings
markdown: kramdown
permalink: pretty
